# Stage 1: Build frontend
FROM    node:alpine as builder
RUN     mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY    package.json /usr/src/app/
RUN     npm install
COPY    . /usr/src/app
RUN     npm run build

# Stage 2: Start nginx
FROM    nginx:alpine as production
ADD     nginx/nginx.conf /etc/nginx/
COPY    --from=builder /usr/src/app/build /var/www
EXPOSE  80
EXPOSE  443
EXPOSE  1337
CMD     ["nginx", "-g", "daemon off;"]
