version: "3.7"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
    volumes:
     - ./backend/postgre/dump.sql:/docker-entrypoint-initdb.d/init.sql   
  
  backend:
    build: ./backend
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=mydb
      - DATABASE_USERNAME=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./backend:/usr/src/api
    depends_on:
      - db

  dev:
    build: frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - 3000:3000
