version: "3.7"
services:
  db:
    container_name: osaamiskiekko_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    volumes:
     - ./backend/postgre/:/docker-entrypoint-initdb.d/
  
  backend:
    container_name: osaamiskiekko_backend
    build: ./backend
    environment:
      - NODE_ENV=development
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
    ports:
      - 1337:1337
    volumes:
      - ./backend:/usr/src/api
    depends_on:
      - db

  dev:
    container_name: osaamiskiekko_frontend
    build: frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:1337
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./.env:/usr/src/app/.env
    ports:
      - 3000:3000
