FIELD_ALIASES = {
"Kasvatusalat": "Humanistinen, kulttuuri ja kasvatus",
"Humanistinen ja kasvatus": "Humanistinen, kulttuuri ja kasvatus",
"Humanistiset alat": "Humanistinen, kulttuuri ja kasvatus",
"Humanistiset ja taidealat": "Humanistinen, kulttuuri ja kasvatus",
"Taiteet ja kulttuurialat": "Humanistinen, kulttuuri ja kasvatus",
"Kulttuuri": "Humanistinen, kulttuuri ja kasvatus",
"Kulttuuriala": "Humanistinen, kulttuuri ja kasvatus",

"Liiketalous": "Liiketalous, hallinto ja yhteiskunta",
"Liiketalous, hallinto ja oikeustieteet": "Liiketalous, hallinto ja yhteiskunta",
"Yhteiskuntatieteiden, liiketalouden ja hallinnon ala": "Liiketalous, hallinto ja yhteiskunta",
"Kauppa, hallinto ja oikeustieteet": "Liiketalous, hallinto ja yhteiskunta",
"Kauppa ja hallinto": "Liiketalous, hallinto ja yhteiskunta",
"Yhteiskunnalliset alat": "Liiketalous, hallinto ja yhteiskunta",
"Yhteiskunta, kansalais- ja järjestötoiminta": "Liiketalous, hallinto ja yhteiskunta",

"Maatalous- ja metsätieteelliset alat": "Maatalous, luonto ja ympäristö",
"Maa- ja metsätalousalat": "Maatalous, luonto ja ympäristö",
"Luonnonvara": "Maatalous, luonto ja ympäristö",
"Luonnonvara- ja ympäristöala": "Maatalous, luonto ja ympäristö",
"Luonto- ja ympäristö": "Maatalous, luonto ja ympäristö",
"Luonnontieteiden ala": "Maatalous, luonto ja ympäristö",
"Luonnontieteet": "Maatalous, luonto ja ympäristö",

"Matkailu-, ravitsemis- ja talousala": "Matkailu, ravitsemus ja talous",
"Matkailu, ravitsemus ja talous": "Matkailu, ravitsemus ja talous",
"Palvelualat": "Matkailu, ravitsemus ja talous",

"Lääketieteet": "Sosiaali, terveys ja liikunta",
"Sosiaali- ja terveysala": "Sosiaali, terveys ja liikunta",
"Terveys- ja hyvinvointialat": "Sosiaali, terveys ja liikunta",
"Sosiaali-, terveys- ja liikunta-ala": "Sosiaali, terveys ja liikunta",
"Sosiaali, terveys ja liikunta": "Sosiaali, terveys ja liikunta",

"Tekniikan alat": "Tekniikka ja liikenne",
"Tekniikka": "Tekniikka ja liikenne",
"Tekniikan ja liikenteen ala": "Tekniikka ja liikenne",
"Tekniikka ja liikenne": "Tekniikka ja liikenne",
"Informaatioteknologia": "Tekniikka ja liikenne",
"Tietojenkäsittely ja tietoliikenne (ICT) Tietojenkäsittely ja tietoliikenne": "Tekniikka ja liikenne",
}
