version: "3.7"

services:
  test:
    build:
      context: ./frontend
    environment:
      - CI=true
    command: npm run test-sonar -- --coverage
    volumes:
    - ./frontend/test-results/:/usr/src/app/coverage/


 
