version: "3.7"

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.production
    ports:
      - 443:443
      - 80:80
    depends_on:
      - backend

  backend:
    command: ./strapi.sh
    build: ./backend
    environment:
      - NODE_ENV=development
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
    ports:
      - 1337:1337 
