version: '3.7'

services:
  robot-db:
    container_name: osaamiskiekko_robot-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: mypass
      POSTGRES_USER: myuser  
    volumes:
     - ./backend/postgre/:/docker-entrypoint-initdb.d/ 

  backend:
    container_name: osaamiskiekko_robot-backend
    command: ./wait-for robot-db:5432 -- ./strapi.sh
    build: ./backend
    environment:
      - NODE_ENV=development
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=robot-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=mydb
      - DATABASE_USERNAME=myuser
      - DATABASE_PASSWORD=mypass
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
    ports:
      - 1337:1337
    depends_on:
      - robot-db

  frontend:
    container_name: osaamiskiekko_robot-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.production
    ports:
      - 443:443
      - 80:80
    depends_on:
      - backend

  robot:
    build: robot
    command: sh -c '/robot/wait-for backend:1337 -t 5 -r 10 --wget -- robot --outputdir /robot/results /robot/tests'
    environment:
      BROWSER: HeadlessChrome
      SERVER: http://frontend/
    volumes:
      - ./robot:/robot
    depends_on:
      - backend
      - frontend