version: '3.7'

services:
  hub:
    image: selenium/hub
    environment:
      GRID_MAX_SESSION: 50
      GRID_UNREGISTER_IF_STILL_DOWN_AFTER: 10000
      GRID_NEW_SESSION_WAIT_TIMEOUT: 5000
      DBUS_SESSION_BUS_ADDRESS: /dev/null
    expose:
      - 4444
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
    ports:
      - 5900:5900
    depends_on:
      - hub

  firefox:
    image: selenium/node-firefox
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
    ports:
      - 5901:5900
    depends_on:
      - hub

  robot-db:
    container_name: osaamiskiekko_robot-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: mypass
      POSTGRES_USER: myuser  
    volumes:
     - ./backend/postgre/:/docker-entrypoint-initdb.d/ 

  backend:
    container_name: osaamiskiekko_robot-backend
    command: ./wait-for robot-db:5432 -- ./strapi.sh
    build: ./backend
    environment:
      - NODE_ENV=development
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=robot-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=mydb
      - DATABASE_USERNAME=myuser
      - DATABASE_PASSWORD=mypass
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
    ports:
      - 1337:1337
    depends_on:
      - robot-db

  frontend:
    container_name: osaamiskiekko_robot-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.production
    ports:
      - 443:443
      - 80:80
    depends_on:
      - backend

  robot:
    build: robot
    command: sh -c '/robot/wait-for hub:4444 -- sleep 5 && python /robot/run.py --outputdir /results'
    environment:
      BROWSER: firefox
      SELENIUM: http://hub:4444/wd/hub
      SERVER: http://frontend/
      API: http://frontend/api/
    volumes:
      - ./robot:/robot:ro
      - ./results/robot:/results:rw
    depends_on:
      - firefox
      - backend
      - frontend
