apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  labels:
    app: osaamiskiekko
    tier: db
    track: stable
    phase: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
