apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: osaamiskiekko
    tier: frontend
    phase: dev
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: osaamiskiekko
      tier: frontend
      track: stable
      phase: dev
  replicas: 1
  template:
    metadata:
      labels:
        app: osaamiskiekko
        tier: frontend
        track: stable
        phase: dev
    spec:
      containers:
      - name: nginx
        image: artifactory.dev.eficode.io/partionosaamiskiekko/osaamiskiekko/frontend_master:e9402845
        lifecycle:
          preStop:
            exec:
              command: ["nginx","-s","quit"]
      imagePullSecrets:
      - name: eficode-artifactory-cred
