# Install nginx-ingress controller in the cluster (https://kubernetes.github.io/ingress-nginx)
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: namespace-ingress
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: $SUBDOMAIN.osaamiskiekko.fi
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
  - host: api.$SUBDOMAIN.osaamiskiekko.fi
    http:
      paths:
      - path: /
        backend:
          serviceName: backend
          servicePort: 1337
