export default [
  {
  "id": 1,
  "url": "https://wiki.humak.fi/display/OS/AHOT-ohjeet+opiskelijoille#",
  "description_fi": "Partiojohtajan peruskoulutus voidaan osittain hyväksilukea Valmentava työote  ja Toimijuuden edistäminen -opintojaksoihin. Opintojaksojen muut osat suoritetaan opintojaksovastaavan antamin tehtävin. ",
  "description_en": "Partiojohtajan peruskoulutus voidaan osittain hyväksilukea Valmentava työote  ja Toimijuuden edistäminen -opintojaksoihin. Opintojaksojen muut osat suoritetaan opintojaksovastaavan antamin tehtävin. _en",
  "description_sv": "Partiojohtajan peruskoulutus voidaan osittain hyväksilukea Valmentava työote  ja Toimijuuden edistäminen -opintojaksoihin. Opintojaksojen muut osat suoritetaan opintojaksovastaavan antamin tehtävin. _sv",
  "competence": {
  "id": 1,
  "identification": "partio-johtajan_peruskoulutus",
  "name_en": "Partiojohtajan peruskoulutus_en",
  "description_en": "Partiojohtaja -peruskoulutus on Suomen Partiolaiset ry:n johtamiskoulutusta. Koulutuksen suorituksesta saatava valtakirja on edellytys tietyissä partiotehtävissä esim. leirinjohtajana toimimiselle. Lähiopetuksen lisäksi kouluttautuja toteuttaa johtamistehtävän, jonka aikana hän johtaa ja ohjaa muita aikuisia tapahtuman tms. toteuttamiseksi. Kouluttautujan tukena johtamistehtävän aikana on aikuinen ohjaaja. Koulutukseen sisältyy maastoyöpyminen, jonka avulla opitaan perusleiritaitoja ja turvallisen maastotoiminnan perusteita. Partiojohtaja -peruskoulutuksen suoritettuaan partiojohtaja osaa perustaidot ja tiedot tapahtuman ja ihmisten johtamisesta, partio-ohjelmasta sekä lippukunnan (paikallisyhdistys) toiminnasta._en",
  "url": null,
  "name_fi": "Partiojohtajan peruskoulutus",
  "name_sv": "Partiojohtajan peruskoulutus_sv",
  "description_fi": "Partiojohtaja -peruskoulutus on Suomen Partiolaiset ry:n johtamiskoulutusta. Koulutuksen suorituksesta saatava valtakirja on edellytys tietyissä partiotehtävissä esim. leirinjohtajana toimimiselle. Lähiopetuksen lisäksi kouluttautuja toteuttaa johtamistehtävän, jonka aikana hän johtaa ja ohjaa muita aikuisia tapahtuman tms. toteuttamiseksi. Kouluttautujan tukena johtamistehtävän aikana on aikuinen ohjaaja. Koulutukseen sisältyy maastoyöpyminen, jonka avulla opitaan perusleiritaitoja ja turvallisen maastotoiminnan perusteita. Partiojohtaja -peruskoulutuksen suoritettuaan partiojohtaja osaa perustaidot ja tiedot tapahtuman ja ihmisten johtamisesta, partio-ohjelmasta sekä lippukunnan (paikallisyhdistys) toiminnasta.",
  "description_sv": "Partiojohtaja -peruskoulutus on Suomen Partiolaiset ry:n johtamiskoulutusta. Koulutuksen suorituksesta saatava valtakirja on edellytys tietyissä partiotehtävissä esim. leirinjohtajana toimimiselle. Lähiopetuksen lisäksi kouluttautuja toteuttaa johtamistehtävän, jonka aikana hän johtaa ja ohjaa muita aikuisia tapahtuman tms. toteuttamiseksi. Kouluttautujan tukena johtamistehtävän aikana on aikuinen ohjaaja. Koulutukseen sisältyy maastoyöpyminen, jonka avulla opitaan perusleiritaitoja ja turvallisen maastotoiminnan perusteita. Partiojohtaja -peruskoulutuksen suoritettuaan partiojohtaja osaa perustaidot ja tiedot tapahtuman ja ihmisten johtamisesta, partio-ohjelmasta sekä lippukunnan (paikallisyhdistys) toiminnasta._sv",
  "nqf": 3,
  "credits": null,
  "organization": 1,
  "created_at": "2019-05-09T09:56:07.855Z",
  "updated_at": "2019-05-15T13:25:31.674Z"
  },
  "academicdegree": {
  "id": 1,
  "identification": "humak-yhteisopedagogi_amk",
  "name_en": "Yhteisöpedagogi (AMK)_EN",
  "name_fi": "Yhteisöpedagogi (AMK)",
  "name_sv": "Yhteisöpedagogi (AMK)_sv",
  "description_en": "Yhteisöpedagogitutkinnosta valmistuu arvostavan kohtaamisen ammattilaisia nuoriso- ja järjestötyöhön sekä yhä moninaisempiin ammatillisiin toimintaympäristöihin yhteiskunnan eri sektoreilla.  Työssä tarvitaan laajaa osaamista ihmisten kasvusta ja kehityksestä, yhteiskunnan rakenteesta ja toiminnasta sekä tietoa kulttuureista ja osallisuudesta. Yhteisöpedagogi (AMK) -tutkinnon voit suorittaa Humakissa kokopäiväisesti päivätoteutuksena tai rajallisen määrän lähijaksoja sisältävinä monimuoto-opintoina._en",
  "description_fi": "Yhteisöpedagogitutkinnosta valmistuu arvostavan kohtaamisen ammattilaisia nuoriso- ja järjestötyöhön sekä yhä moninaisempiin ammatillisiin toimintaympäristöihin yhteiskunnan eri sektoreilla.  Työssä tarvitaan laajaa osaamista ihmisten kasvusta ja kehityksestä, yhteiskunnan rakenteesta ja toiminnasta sekä tietoa kulttuureista ja osallisuudesta. Yhteisöpedagogi (AMK) -tutkinnon voit suorittaa Humakissa kokopäiväisesti päivätoteutuksena tai rajallisen määrän lähijaksoja sisältävinä monimuoto-opintoina.",
  "description_sv": "Yhteisöpedagogitutkinnosta valmistuu arvostavan kohtaamisen ammattilaisia nuoriso- ja järjestötyöhön sekä yhä moninaisempiin ammatillisiin toimintaympäristöihin yhteiskunnan eri sektoreilla.  Työssä tarvitaan laajaa osaamista ihmisten kasvusta ja kehityksestä, yhteiskunnan rakenteesta ja toiminnasta sekä tietoa kulttuureista ja osallisuudesta. Yhteisöpedagogi (AMK) -tutkinnon voit suorittaa Humakissa kokopäiväisesti päivätoteutuksena tai rajallisen määrän lähijaksoja sisältävinä monimuoto-opintoina._en",
  "url": null,
  "credits": null,
  "nqf": 4,
  "school": 1,
  "fieldofstudy": 1,
  "created_at": "2019-05-09T10:01:07.693Z",
  "updated_at": "2019-05-15T12:46:03.550Z"
  },
  "created_at": "2019-05-09T10:01:27.377Z",
  "updated_at": "2019-05-24T10:00:03.895Z"
  },
  {
  "id": 2,
  "url": "https://wiki.humak.fi/display/OS/AHOT-ohjeet+opiskelijoille",
  "description_fi": "Valmentajakoulutus voidaan hyväksilukea Valmentava työote -opintojaksoon. Hyväksilukuun vaaditaan lisäksi näyttö kokonaisuuden keskeisten asioiden hallinnasta NQF6-tasolla. Jos samalla ei hyväksilueta partionjohtajakoulutusta, hyväksiluku edellyttää myös  toimintaa valmentajan pestissä partiossa.",
  "description_en": "Valmentajakoulutus voidaan hyväksilukea Valmentava työote -opintojaksoon. Hyväksilukuun vaaditaan lisäksi näyttö kokonaisuuden keskeisten asioiden hallinnasta NQF6-tasolla. Jos samalla ei hyväksilueta partionjohtajakoulutusta, hyväksiluku edellyttää myös  toimintaa valmentajan pestissä partiossa._en",
  "description_sv": "Valmentajakoulutus voidaan hyväksilukea Valmentava työote -opintojaksoon. Hyväksilukuun vaaditaan lisäksi näyttö kokonaisuuden keskeisten asioiden hallinnasta NQF6-tasolla. Jos samalla ei hyväksilueta partionjohtajakoulutusta, hyväksiluku edellyttää myös  toimintaa valmentajan pestissä partiossa._sv",
  "competence": {
  "id": 2,
  "identification": "partio-valmentajakoulutus",
  "name_en": "Valmentajakoulutus_EN",
  "description_en": "Valmentaja -koulutuksen käytyään partiojohtaja ymmärtää valmentamisen käsitteen ja osaa soveltaa valmentamisen toimintatapoja ja työkaluja pestissään. Hän ymmärtää partion aluetyön ja lippukuntatuen merkityksen sekä perusteet, ja osaa valmentaa lippukuntia kohti laadukkaampaa partiota. Hän osaa tukea lippukuntatoimijoita pesteissään ja varmistaa, että partion strategia sekä ajankohtaiset teemat nivotuvat osaksi lippukuntatoimintaa. Kouluttautuja osaa tukea ja valmentaa lippukunnan johtajistoa lippukunnan kokonaisuuden johtamisessa, partiokasvatuksen toteuttamisessa, henkilöstöresurssien kehittämisessä, lippukunnan lyhyen ja pitkän tähtäimen suunnittelussa ja erilaisten haasteiden ratkaisemisessa._en",
  "url": null,
  "name_fi": "Valmentajakoulutus",
  "name_sv": "Valmentajakoulutus_sv",
  "description_fi": "Valmentaja -koulutuksen käytyään partiojohtaja ymmärtää valmentamisen käsitteen ja osaa soveltaa valmentamisen toimintatapoja ja työkaluja pestissään. Hän ymmärtää partion aluetyön ja lippukuntatuen merkityksen sekä perusteet, ja osaa valmentaa lippukuntia kohti laadukkaampaa partiota. Hän osaa tukea lippukuntatoimijoita pesteissään ja varmistaa, että partion strategia sekä ajankohtaiset teemat nivotuvat osaksi lippukuntatoimintaa. Kouluttautuja osaa tukea ja valmentaa lippukunnan johtajistoa lippukunnan kokonaisuuden johtamisessa, partiokasvatuksen toteuttamisessa, henkilöstöresurssien kehittämisessä, lippukunnan lyhyen ja pitkän tähtäimen suunnittelussa ja erilaisten haasteiden ratkaisemisessa.",
  "description_sv": "Valmentaja -koulutuksen käytyään partiojohtaja ymmärtää valmentamisen käsitteen ja osaa soveltaa valmentamisen toimintatapoja ja työkaluja pestissään. Hän ymmärtää partion aluetyön ja lippukuntatuen merkityksen sekä perusteet, ja osaa valmentaa lippukuntia kohti laadukkaampaa partiota. Hän osaa tukea lippukuntatoimijoita pesteissään ja varmistaa, että partion strategia sekä ajankohtaiset teemat nivotuvat osaksi lippukuntatoimintaa. Kouluttautuja osaa tukea ja valmentaa lippukunnan johtajistoa lippukunnan kokonaisuuden johtamisessa, partiokasvatuksen toteuttamisessa, henkilöstöresurssien kehittämisessä, lippukunnan lyhyen ja pitkän tähtäimen suunnittelussa ja erilaisten haasteiden ratkaisemisessa._sv",
  "nqf": 3,
  "credits": null,
  "organization": null,
  "created_at": "2019-05-09T09:58:26.655Z",
  "updated_at": "2019-05-13T09:27:55.567Z"
  },
  "academicdegree": {
  "id": 1,
  "identification": "humak-yhteisopedagogi_amk",
  "name_en": "Yhteisöpedagogi (AMK)_EN",
  "name_fi": "Yhteisöpedagogi (AMK)",
  "name_sv": "Yhteisöpedagogi (AMK)_sv",
  "description_en": "Yhteisöpedagogitutkinnosta valmistuu arvostavan kohtaamisen ammattilaisia nuoriso- ja järjestötyöhön sekä yhä moninaisempiin ammatillisiin toimintaympäristöihin yhteiskunnan eri sektoreilla.  Työssä tarvitaan laajaa osaamista ihmisten kasvusta ja kehityksestä, yhteiskunnan rakenteesta ja toiminnasta sekä tietoa kulttuureista ja osallisuudesta. Yhteisöpedagogi (AMK) -tutkinnon voit suorittaa Humakissa kokopäiväisesti päivätoteutuksena tai rajallisen määrän lähijaksoja sisältävinä monimuoto-opintoina._en",
  "description_fi": "Yhteisöpedagogitutkinnosta valmistuu arvostavan kohtaamisen ammattilaisia nuoriso- ja järjestötyöhön sekä yhä moninaisempiin ammatillisiin toimintaympäristöihin yhteiskunnan eri sektoreilla.  Työssä tarvitaan laajaa osaamista ihmisten kasvusta ja kehityksestä, yhteiskunnan rakenteesta ja toiminnasta sekä tietoa kulttuureista ja osallisuudesta. Yhteisöpedagogi (AMK) -tutkinnon voit suorittaa Humakissa kokopäiväisesti päivätoteutuksena tai rajallisen määrän lähijaksoja sisältävinä monimuoto-opintoina.",
  "description_sv": "Yhteisöpedagogitutkinnosta valmistuu arvostavan kohtaamisen ammattilaisia nuoriso- ja järjestötyöhön sekä yhä moninaisempiin ammatillisiin toimintaympäristöihin yhteiskunnan eri sektoreilla.  Työssä tarvitaan laajaa osaamista ihmisten kasvusta ja kehityksestä, yhteiskunnan rakenteesta ja toiminnasta sekä tietoa kulttuureista ja osallisuudesta. Yhteisöpedagogi (AMK) -tutkinnon voit suorittaa Humakissa kokopäiväisesti päivätoteutuksena tai rajallisen määrän lähijaksoja sisältävinä monimuoto-opintoina._en",
  "url": null,
  "credits": null,
  "nqf": 4,
  "school": 1,
  "fieldofstudy": 1,
  "created_at": "2019-05-09T10:01:07.693Z",
  "updated_at": "2019-05-15T12:46:03.550Z"
  },
  "created_at": "2019-05-09T10:02:00.360Z",
  "updated_at": "2019-05-24T10:00:09.616Z"
  }
  ]
