export default [
  {
    "id": 9,
    "url": null,
    "description_fi": "s1d1-o1c2",
    "description_en": "s1d1-o1c2",
    "description_sv": "s1d1-o1c2",
    "competence": {
      "id": 7,
      "identification": "org1-comp2",
      "name_en": "org1-comp2",
      "description_en": null,
      "url": null,
      "name_fi": "org1-comp2",
      "name_sv": "org1-comp2",
      "description_fi": null,
      "description_sv": null,
      "nqf": 4,
      "credits": null,
      "organization": 4,
      "created_at": "2019-06-03T08:30:14.434Z",
      "updated_at": "2019-06-03T08:38:33.122Z"
    },
    "academicdegree": {
      "id": 3,
      "identification": "school1-deg1",
      "name_en": "school1-deg1_en",
      "name_fi": "school1-deg1_fi",
      "name_sv": "school1-deg1_sv",
      "description_en": "school1-deg1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec enim lectus, luctus nec lorem id, laoreet vestibulum justo. Curabitur imperdiet ac magna eu ornare. Ut vehicula eleifend vestibulum. Mauris eget purus et libero finibus malesuada. Maecenas magna libero, pellentesque cursus varius sed, aliquam eu felis. Maecenas congue augue vehicula massa tincidunt tincidunt. Suspendisse potenti. Suspendisse vulputate nisi eget nunc interdum ultricies. Etiam urna velit, imperdiet eget sollicitudin sit amet, suscipit eget augue. Ut commodo enim nec dapibus porttitor. Donec id congue tortor, a ullamcorper metus. Vivamus vel eros vel orci auctor lobortis. Cras ac neque diam.\n\nVivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar._en",
      "description_fi": "school1-deg1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec enim lectus, luctus nec lorem id, laoreet vestibulum justo. Curabitur imperdiet ac magna eu ornare. Ut vehicula eleifend vestibulum. Mauris eget purus et libero finibus malesuada. Maecenas magna libero, pellentesque cursus varius sed, aliquam eu felis. Maecenas congue augue vehicula massa tincidunt tincidunt. Suspendisse potenti. Suspendisse vulputate nisi eget nunc interdum ultricies. Etiam urna velit, imperdiet eget sollicitudin sit amet, suscipit eget augue. Ut commodo enim nec dapibus porttitor. Donec id congue tortor, a ullamcorper metus. Vivamus vel eros vel orci auctor lobortis. Cras ac neque diam.\n\nVivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar._fi",
      "description_sv": "school1-deg1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec enim lectus, luctus nec lorem id, laoreet vestibulum justo. Curabitur imperdiet ac magna eu ornare. Ut vehicula eleifend vestibulum. Mauris eget purus et libero finibus malesuada. Maecenas magna libero, pellentesque cursus varius sed, aliquam eu felis. Maecenas congue augue vehicula massa tincidunt tincidunt. Suspendisse potenti. Suspendisse vulputate nisi eget nunc interdum ultricies. Etiam urna velit, imperdiet eget sollicitudin sit amet, suscipit eget augue. Ut commodo enim nec dapibus porttitor. Donec id congue tortor, a ullamcorper metus. Vivamus vel eros vel orci auctor lobortis. Cras ac neque diam.\n\nVivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar._sv",
      "url": null,
      "credits": 14,
      "nqf": 3,
      "school": 7,
      "fieldofstudy": 2,
      "created_at": "2019-06-03T08:31:16.758Z",
      "updated_at": "2019-06-03T08:39:35.832Z"
    },
    "created_at": "2019-06-03T08:33:26.293Z",
    "updated_at": "2019-06-03T08:36:14.783Z",
    "identification": "s1d1-o1c2"
  },
  {
    "id": 10,
    "url": null,
    "description_fi": "s1d1-o2c1",
    "description_en": "s1d1-o2c1",
    "description_sv": "s1d1-o2c1",
    "competence": {
      "id": 8,
      "identification": "org2-comp1",
      "name_en": "org2-comp1",
      "description_en": null,
      "url": null,
      "name_fi": "org2-comp1",
      "name_sv": "org2-comp1",
      "description_fi": null,
      "description_sv": null,
      "nqf": 1,
      "credits": null,
      "organization": 5,
      "created_at": "2019-06-03T08:30:26.765Z",
      "updated_at": "2019-06-03T08:30:26.783Z"
    },
    "academicdegree": {
      "id": 3,
      "identification": "school1-deg1",
      "name_en": "school1-deg1_en",
      "name_fi": "school1-deg1_fi",
      "name_sv": "school1-deg1_sv",
      "description_en": "school1-deg1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec enim lectus, luctus nec lorem id, laoreet vestibulum justo. Curabitur imperdiet ac magna eu ornare. Ut vehicula eleifend vestibulum. Mauris eget purus et libero finibus malesuada. Maecenas magna libero, pellentesque cursus varius sed, aliquam eu felis. Maecenas congue augue vehicula massa tincidunt tincidunt. Suspendisse potenti. Suspendisse vulputate nisi eget nunc interdum ultricies. Etiam urna velit, imperdiet eget sollicitudin sit amet, suscipit eget augue. Ut commodo enim nec dapibus porttitor. Donec id congue tortor, a ullamcorper metus. Vivamus vel eros vel orci auctor lobortis. Cras ac neque diam.\n\nVivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar._en",
      "description_fi": "school1-deg1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec enim lectus, luctus nec lorem id, laoreet vestibulum justo. Curabitur imperdiet ac magna eu ornare. Ut vehicula eleifend vestibulum. Mauris eget purus et libero finibus malesuada. Maecenas magna libero, pellentesque cursus varius sed, aliquam eu felis. Maecenas congue augue vehicula massa tincidunt tincidunt. Suspendisse potenti. Suspendisse vulputate nisi eget nunc interdum ultricies. Etiam urna velit, imperdiet eget sollicitudin sit amet, suscipit eget augue. Ut commodo enim nec dapibus porttitor. Donec id congue tortor, a ullamcorper metus. Vivamus vel eros vel orci auctor lobortis. Cras ac neque diam.\n\nVivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar._fi",
      "description_sv": "school1-deg1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec enim lectus, luctus nec lorem id, laoreet vestibulum justo. Curabitur imperdiet ac magna eu ornare. Ut vehicula eleifend vestibulum. Mauris eget purus et libero finibus malesuada. Maecenas magna libero, pellentesque cursus varius sed, aliquam eu felis. Maecenas congue augue vehicula massa tincidunt tincidunt. Suspendisse potenti. Suspendisse vulputate nisi eget nunc interdum ultricies. Etiam urna velit, imperdiet eget sollicitudin sit amet, suscipit eget augue. Ut commodo enim nec dapibus porttitor. Donec id congue tortor, a ullamcorper metus. Vivamus vel eros vel orci auctor lobortis. Cras ac neque diam.\n\nVivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar._sv",
      "url": null,
      "credits": 14,
      "nqf": 3,
      "school": 7,
      "fieldofstudy": 2,
      "created_at": "2019-06-03T08:31:16.758Z",
      "updated_at": "2019-06-03T08:39:35.832Z"
    },
    "created_at": "2019-06-03T08:33:55.943Z",
    "updated_at": "2019-06-03T08:36:14.783Z",
    "identification": "s1d1-o2c1"
  },
  {
    "id": 8,
    "url": null,
    "description_fi": "s1d1-o1c1 Vivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar.",
    "description_en": "s1d1-o1c1 Vivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar.",
    "description_sv": "s1d1-o1c1 Vivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar.",
    "competence": {
      "id": 6,
      "identification": "org1-comp1",
      "name_en": "org1-comp1_en",
      "description_en": "org1-comp1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec enim lectus, luctus nec lorem id, laoreet vestibulum justo. Curabitur imperdiet ac magna eu ornare. Ut vehicula eleifend vestibulum. Mauris eget purus et libero finibus malesuada. Maecenas magna libero, pellentesque cursus varius sed, aliquam eu felis. Maecenas congue augue vehicula massa tincidunt tincidunt. Suspendisse potenti. Suspendisse vulputate nisi eget nunc interdum ultricies. Etiam urna velit, imperdiet eget sollicitudin sit amet, suscipit eget augue. Ut commodo enim nec dapibus porttitor. Donec id congue tortor, a ullamcorper metus. Vivamus vel eros vel orci auctor lobortis. Cras ac neque diam.\n\nVivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar._en",
      "url": null,
      "name_fi": "org1-comp1_fi",
      "name_sv": "org1-comp1_sv",
      "description_fi": "org1-comp1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec enim lectus, luctus nec lorem id, laoreet vestibulum justo. Curabitur imperdiet ac magna eu ornare. Ut vehicula eleifend vestibulum. Mauris eget purus et libero finibus malesuada. Maecenas magna libero, pellentesque cursus varius sed, aliquam eu felis. Maecenas congue augue vehicula massa tincidunt tincidunt. Suspendisse potenti. Suspendisse vulputate nisi eget nunc interdum ultricies. Etiam urna velit, imperdiet eget sollicitudin sit amet, suscipit eget augue. Ut commodo enim nec dapibus porttitor. Donec id congue tortor, a ullamcorper metus. Vivamus vel eros vel orci auctor lobortis. Cras ac neque diam.\n\nVivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar._fi",
      "description_sv": "org1-comp1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec enim lectus, luctus nec lorem id, laoreet vestibulum justo. Curabitur imperdiet ac magna eu ornare. Ut vehicula eleifend vestibulum. Mauris eget purus et libero finibus malesuada. Maecenas magna libero, pellentesque cursus varius sed, aliquam eu felis. Maecenas congue augue vehicula massa tincidunt tincidunt. Suspendisse potenti. Suspendisse vulputate nisi eget nunc interdum ultricies. Etiam urna velit, imperdiet eget sollicitudin sit amet, suscipit eget augue. Ut commodo enim nec dapibus porttitor. Donec id congue tortor, a ullamcorper metus. Vivamus vel eros vel orci auctor lobortis. Cras ac neque diam.\n\nVivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar._sv",
      "nqf": 1,
      "credits": 4,
      "organization": 4,
      "created_at": "2019-06-03T08:30:03.300Z",
      "updated_at": "2019-06-03T08:38:33.122Z"
    },
    "academicdegree": {
      "id": 3,
      "identification": "school1-deg1",
      "name_en": "school1-deg1_en",
      "name_fi": "school1-deg1_fi",
      "name_sv": "school1-deg1_sv",
      "description_en": "school1-deg1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec enim lectus, luctus nec lorem id, laoreet vestibulum justo. Curabitur imperdiet ac magna eu ornare. Ut vehicula eleifend vestibulum. Mauris eget purus et libero finibus malesuada. Maecenas magna libero, pellentesque cursus varius sed, aliquam eu felis. Maecenas congue augue vehicula massa tincidunt tincidunt. Suspendisse potenti. Suspendisse vulputate nisi eget nunc interdum ultricies. Etiam urna velit, imperdiet eget sollicitudin sit amet, suscipit eget augue. Ut commodo enim nec dapibus porttitor. Donec id congue tortor, a ullamcorper metus. Vivamus vel eros vel orci auctor lobortis. Cras ac neque diam.\n\nVivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar._en",
      "description_fi": "school1-deg1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec enim lectus, luctus nec lorem id, laoreet vestibulum justo. Curabitur imperdiet ac magna eu ornare. Ut vehicula eleifend vestibulum. Mauris eget purus et libero finibus malesuada. Maecenas magna libero, pellentesque cursus varius sed, aliquam eu felis. Maecenas congue augue vehicula massa tincidunt tincidunt. Suspendisse potenti. Suspendisse vulputate nisi eget nunc interdum ultricies. Etiam urna velit, imperdiet eget sollicitudin sit amet, suscipit eget augue. Ut commodo enim nec dapibus porttitor. Donec id congue tortor, a ullamcorper metus. Vivamus vel eros vel orci auctor lobortis. Cras ac neque diam.\n\nVivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar._fi",
      "description_sv": "school1-deg1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec enim lectus, luctus nec lorem id, laoreet vestibulum justo. Curabitur imperdiet ac magna eu ornare. Ut vehicula eleifend vestibulum. Mauris eget purus et libero finibus malesuada. Maecenas magna libero, pellentesque cursus varius sed, aliquam eu felis. Maecenas congue augue vehicula massa tincidunt tincidunt. Suspendisse potenti. Suspendisse vulputate nisi eget nunc interdum ultricies. Etiam urna velit, imperdiet eget sollicitudin sit amet, suscipit eget augue. Ut commodo enim nec dapibus porttitor. Donec id congue tortor, a ullamcorper metus. Vivamus vel eros vel orci auctor lobortis. Cras ac neque diam.\n\nVivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar._sv",
      "url": null,
      "credits": 14,
      "nqf": 3,
      "school": 7,
      "fieldofstudy": 2,
      "created_at": "2019-06-03T08:31:16.758Z",
      "updated_at": "2019-06-03T08:39:35.832Z"
    },
    "created_at": "2019-06-03T08:32:56.764Z",
    "updated_at": "2019-06-03T08:36:42.946Z",
    "identification": "s1d1-o1c1"
  },
  {
    "id": 11,
    "url": null,
    "description_fi": "s2d1-o1c1",
    "description_en": "s2d1-o1c1",
    "description_sv": "s2d1-o1c1",
    "competence": {
      "id": 6,
      "identification": "org1-comp1",
      "name_en": "org1-comp1_en",
      "description_en": "org1-comp1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec enim lectus, luctus nec lorem id, laoreet vestibulum justo. Curabitur imperdiet ac magna eu ornare. Ut vehicula eleifend vestibulum. Mauris eget purus et libero finibus malesuada. Maecenas magna libero, pellentesque cursus varius sed, aliquam eu felis. Maecenas congue augue vehicula massa tincidunt tincidunt. Suspendisse potenti. Suspendisse vulputate nisi eget nunc interdum ultricies. Etiam urna velit, imperdiet eget sollicitudin sit amet, suscipit eget augue. Ut commodo enim nec dapibus porttitor. Donec id congue tortor, a ullamcorper metus. Vivamus vel eros vel orci auctor lobortis. Cras ac neque diam.\n\nVivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar._en",
      "url": null,
      "name_fi": "org1-comp1_fi",
      "name_sv": "org1-comp1_sv",
      "description_fi": "org1-comp1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec enim lectus, luctus nec lorem id, laoreet vestibulum justo. Curabitur imperdiet ac magna eu ornare. Ut vehicula eleifend vestibulum. Mauris eget purus et libero finibus malesuada. Maecenas magna libero, pellentesque cursus varius sed, aliquam eu felis. Maecenas congue augue vehicula massa tincidunt tincidunt. Suspendisse potenti. Suspendisse vulputate nisi eget nunc interdum ultricies. Etiam urna velit, imperdiet eget sollicitudin sit amet, suscipit eget augue. Ut commodo enim nec dapibus porttitor. Donec id congue tortor, a ullamcorper metus. Vivamus vel eros vel orci auctor lobortis. Cras ac neque diam.\n\nVivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar._fi",
      "description_sv": "org1-comp1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec enim lectus, luctus nec lorem id, laoreet vestibulum justo. Curabitur imperdiet ac magna eu ornare. Ut vehicula eleifend vestibulum. Mauris eget purus et libero finibus malesuada. Maecenas magna libero, pellentesque cursus varius sed, aliquam eu felis. Maecenas congue augue vehicula massa tincidunt tincidunt. Suspendisse potenti. Suspendisse vulputate nisi eget nunc interdum ultricies. Etiam urna velit, imperdiet eget sollicitudin sit amet, suscipit eget augue. Ut commodo enim nec dapibus porttitor. Donec id congue tortor, a ullamcorper metus. Vivamus vel eros vel orci auctor lobortis. Cras ac neque diam.\n\nVivamus luctus dignissim odio, sit amet tristique nisl bibendum ac. Quisque ullamcorper eros et hendrerit scelerisque. Pellentesque vehicula ex urna, ut tempus ante efficitur a. Aliquam metus nibh, vulputate a augue ac, auctor ullamcorper mi. Donec vitae facilisis ante, sagittis egestas mi. Nunc dignissim velit vitae ullamcorper suscipit. Sed posuere, est non tempor molestie, elit nibh consectetur metus, sit amet tincidunt ante nibh quis ex. Sed vestibulum at dolor vel pulvinar._sv",
      "nqf": 1,
      "credits": 4,
      "organization": 4,
      "created_at": "2019-06-03T08:30:03.300Z",
      "updated_at": "2019-06-03T08:38:33.122Z"
    },
    "academicdegree": {
      "id": 6,
      "identification": "school2-deg1",
      "name_en": "school2-deg1",
      "name_fi": "school2-deg1",
      "name_sv": "school2-deg1",
      "description_en": "school2-deg1",
      "description_fi": "school2-deg1",
      "description_sv": "school2-deg1",
      "url": null,
      "credits": null,
      "nqf": 2,
      "school": 8,
      "fieldofstudy": 2,
      "created_at": "2019-06-03T08:32:25.497Z",
      "updated_at": "2019-06-03T08:32:25.512Z"
    },
    "created_at": "2019-06-03T08:34:30.247Z",
    "updated_at": "2019-06-03T08:36:42.946Z",
    "identification": "s2d1-o1c1"
  },
  {
    "id": 12,
    "url": null,
    "description_fi": "s2d1-o2c3",
    "description_en": "s2d1-o2c3",
    "description_sv": "s2d1-o2c3",
    "competence": {
      "id": 10,
      "identification": "org2-comp3",
      "name_en": "org2-comp3",
      "description_en": null,
      "url": null,
      "name_fi": "org2-comp3",
      "name_sv": "org2-comp3",
      "description_fi": null,
      "description_sv": null,
      "nqf": 2,
      "credits": null,
      "organization": 5,
      "created_at": "2019-06-03T08:30:52.171Z",
      "updated_at": "2019-06-03T08:30:52.191Z"
    },
    "academicdegree": {
      "id": 6,
      "identification": "school2-deg1",
      "name_en": "school2-deg1",
      "name_fi": "school2-deg1",
      "name_sv": "school2-deg1",
      "description_en": "school2-deg1",
      "description_fi": "school2-deg1",
      "description_sv": "school2-deg1",
      "url": null,
      "credits": null,
      "nqf": 2,
      "school": 8,
      "fieldofstudy": 2,
      "created_at": "2019-06-03T08:32:25.497Z",
      "updated_at": "2019-06-03T08:32:25.512Z"
    },
    "created_at": "2019-06-03T08:34:52.695Z",
    "updated_at": "2019-06-03T08:34:52.710Z",
    "identification": "s2d1-o2c3"
  }
]
