export default [
  {
  "id": 1,
  "url": "https://wiki.humak.fi/display/OS/AHOT-ohjeet+opiskelijoille#",
  "description_fi": "Partiojohtajan peruskoulutus voidaan osittain hyväksilukea Valmentava työote  ja Toimijuuden edistäminen -opintojaksoihin. Opintojaksojen muut osat suoritetaan opintojaksovastaavan antamin tehtävin. ",
  "description_en": "Partiojohtajan peruskoulutus voidaan osittain hyväksilukea Valmentava työote  ja Toimijuuden edistäminen -opintojaksoihin. Opintojaksojen muut osat suoritetaan opintojaksovastaavan antamin tehtävin. _en",
  "description_sv": "Partiojohtajan peruskoulutus voidaan osittain hyväksilukea Valmentava työote  ja Toimijuuden edistäminen -opintojaksoihin. Opintojaksojen muut osat suoritetaan opintojaksovastaavan antamin tehtävin. _sv",
  "competence": {
  "id": 1,
  "identification": "partio-johtajan_peruskoulutus",
  "name_en": "Partiojohtajan peruskoulutus_en",
  "description_en": "Partiojohtaja -peruskoulutus on Suomen Partiolaiset ry:n johtamiskoulutusta. Koulutuksen suorituksesta saatava valtakirja on edellytys tietyissä partiotehtävissä esim. leirinjohtajana toimimiselle. Lähiopetuksen lisäksi kouluttautuja toteuttaa johtamistehtävän, jonka aikana hän johtaa ja ohjaa muita aikuisia tapahtuman tms. toteuttamiseksi. Kouluttautujan tukena johtamistehtävän aikana on aikuinen ohjaaja. Koulutukseen sisältyy maastoyöpyminen, jonka avulla opitaan perusleiritaitoja ja turvallisen maastotoiminnan perusteita. Partiojohtaja -peruskoulutuksen suoritettuaan partiojohtaja osaa perustaidot ja tiedot tapahtuman ja ihmisten johtamisesta, partio-ohjelmasta sekä lippukunnan (paikallisyhdistys) toiminnasta._en",
  "url": null,
  "name_fi": "Partiojohtajan peruskoulutus",
  "name_sv": "Partiojohtajan peruskoulutus_sv",
  "description_fi": "Partiojohtaja -peruskoulutus on Suomen Partiolaiset ry:n johtamiskoulutusta. Koulutuksen suorituksesta saatava valtakirja on edellytys tietyissä partiotehtävissä esim. leirinjohtajana toimimiselle. Lähiopetuksen lisäksi kouluttautuja toteuttaa johtamistehtävän, jonka aikana hän johtaa ja ohjaa muita aikuisia tapahtuman tms. toteuttamiseksi. Kouluttautujan tukena johtamistehtävän aikana on aikuinen ohjaaja. Koulutukseen sisältyy maastoyöpyminen, jonka avulla opitaan perusleiritaitoja ja turvallisen maastotoiminnan perusteita. Partiojohtaja -peruskoulutuksen suoritettuaan partiojohtaja osaa perustaidot ja tiedot tapahtuman ja ihmisten johtamisesta, partio-ohjelmasta sekä lippukunnan (paikallisyhdistys) toiminnasta.",
  "description_sv": "Partiojohtaja -peruskoulutus on Suomen Partiolaiset ry:n johtamiskoulutusta. Koulutuksen suorituksesta saatava valtakirja on edellytys tietyissä partiotehtävissä esim. leirinjohtajana toimimiselle. Lähiopetuksen lisäksi kouluttautuja toteuttaa johtamistehtävän, jonka aikana hän johtaa ja ohjaa muita aikuisia tapahtuman tms. toteuttamiseksi. Kouluttautujan tukena johtamistehtävän aikana on aikuinen ohjaaja. Koulutukseen sisältyy maastoyöpyminen, jonka avulla opitaan perusleiritaitoja ja turvallisen maastotoiminnan perusteita. Partiojohtaja -peruskoulutuksen suoritettuaan partiojohtaja osaa perustaidot ja tiedot tapahtuman ja ihmisten johtamisesta, partio-ohjelmasta sekä lippukunnan (paikallisyhdistys) toiminnasta._sv",
  "nqf": {
    "id": 3,
    "name_en": "Erikoisammattitukinnot_en",
    "name_fi": "Erikoisammattitukinnot",
    "name_sv": "Erikoisammattitukinnot_sv",
    "level": "5",
    "created_at": "2019-05-09T09:57:47.742Z",
    "updated_at": "2019-05-13T09:24:32.452Z"
  },
  "credits": null,
  "organization": {
    "id": 1,
    "name_en": "The Guides and Scouts of Finland",
    "name_fi": "Suomen Partiolaiset – Finlands Scouter ry",
    "name_sv": "Suomen Partiolaiset – Finlands Scouter ry",
    "description_fi": "Suomen Partiolaiset – Finlands Scouter ry on partioliikkeen keskusjärjestö Suomessa ja Suomen suurin nuorisojärjestö.",
    "description_en": "Suomen Partiolaiset – Finlands Scouter ry on partioliikkeen keskusjärjestö Suomessa ja Suomen suurin nuorisojärjestö._en",
    "description_sv": "Suomen Partiolaiset – Finlands Scouter ry on partioliikkeen keskusjärjestö Suomessa ja Suomen suurin nuorisojärjestö._sv",
    "url": "https://www.partio.fi",
    "logoUrl": null,
    "created_at": "2019-05-09T09:55:05.648Z",
    "updated_at": "2019-05-15T13:25:31.650Z",
  },
  "created_at": "2019-05-09T09:56:07.855Z",
  "updated_at": "2019-05-15T13:25:31.674Z"
  },
  "academicdegree": {
  "id": 1,
  "identification": "humak-yhteisopedagogi_amk",
  "name_en": "Yhteisöpedagogi (AMK)_EN",
  "name_fi": "Yhteisöpedagogi (AMK)",
  "name_sv": "Yhteisöpedagogi (AMK)_sv",
  "description_en": "Yhteisöpedagogitutkinnosta valmistuu arvostavan kohtaamisen ammattilaisia nuoriso- ja järjestötyöhön sekä yhä moninaisempiin ammatillisiin toimintaympäristöihin yhteiskunnan eri sektoreilla.  Työssä tarvitaan laajaa osaamista ihmisten kasvusta ja kehityksestä, yhteiskunnan rakenteesta ja toiminnasta sekä tietoa kulttuureista ja osallisuudesta. Yhteisöpedagogi (AMK) -tutkinnon voit suorittaa Humakissa kokopäiväisesti päivätoteutuksena tai rajallisen määrän lähijaksoja sisältävinä monimuoto-opintoina._en",
  "description_fi": "Yhteisöpedagogitutkinnosta valmistuu arvostavan kohtaamisen ammattilaisia nuoriso- ja järjestötyöhön sekä yhä moninaisempiin ammatillisiin toimintaympäristöihin yhteiskunnan eri sektoreilla.  Työssä tarvitaan laajaa osaamista ihmisten kasvusta ja kehityksestä, yhteiskunnan rakenteesta ja toiminnasta sekä tietoa kulttuureista ja osallisuudesta. Yhteisöpedagogi (AMK) -tutkinnon voit suorittaa Humakissa kokopäiväisesti päivätoteutuksena tai rajallisen määrän lähijaksoja sisältävinä monimuoto-opintoina.",
  "description_sv": "Yhteisöpedagogitutkinnosta valmistuu arvostavan kohtaamisen ammattilaisia nuoriso- ja järjestötyöhön sekä yhä moninaisempiin ammatillisiin toimintaympäristöihin yhteiskunnan eri sektoreilla.  Työssä tarvitaan laajaa osaamista ihmisten kasvusta ja kehityksestä, yhteiskunnan rakenteesta ja toiminnasta sekä tietoa kulttuureista ja osallisuudesta. Yhteisöpedagogi (AMK) -tutkinnon voit suorittaa Humakissa kokopäiväisesti päivätoteutuksena tai rajallisen määrän lähijaksoja sisältävinä monimuoto-opintoina._en",
  "url": null,
  "credits": null,
  "nqf": {
    "id": 3,
    "name_en": "Erikoisammattitukinnot_en",
    "name_fi": "Erikoisammattitukinnot",
    "name_sv": "Erikoisammattitukinnot_sv",
    "level": "5",
    "created_at": "2019-05-09T09:57:47.742Z",
    "updated_at": "2019-05-13T09:24:32.452Z"
  },
  "school": {
    id: 1,
    name_en: 'Humanistinen ammattikorkeakoulu_en',
    name_fi: 'Humanistinen ammattikorkeakoulu',
    name_sv: 'Humanistinen ammattikorkeakoulu_sv',
    description_en: 'Humanistinen ammattikorkeakoulu (Humak) on vahvasti profiloitunut, valtakunnallinen ammattikorkeakoulu, joka on erikoistunut järjestö- ja nuorisotyön, työyhteisöjen kehittämisen, kulttuurituotannon ja luovan toimialan yrittäjyyden sekä tulkkausalan erityisosaamisen ja toiminnan kehittämiseen. Humakissa on 1500 opiskelijaa ja noin 130 asiantuntijaa eri tehtävissä._en',
    description_fi: 'Humanistinen ammattikorkeakoulu (Humak) on vahvasti profiloitunut, valtakunnallinen ammattikorkeakoulu, joka on erikoistunut järjestö- ja nuorisotyön, työyhteisöjen kehittämisen, kulttuurituotannon ja luovan toimialan yrittäjyyden sekä tulkkausalan erityisosaamisen ja toiminnan kehittämiseen. Humakissa on 1500 opiskelijaa ja noin 130 asiantuntijaa eri tehtävissä.',
    description_sv: 'Humanistinen ammattikorkeakoulu (Humak) on vahvasti profiloitunut, valtakunnallinen ammattikorkeakoulu, joka on erikoistunut järjestö- ja nuorisotyön, työyhteisöjen kehittämisen, kulttuurituotannon ja luovan toimialan yrittäjyyden sekä tulkkausalan erityisosaamisen ja toiminnan kehittämiseen. Humakissa on 1500 opiskelijaa ja noin 130 asiantuntijaa eri tehtävissä._sv',
    url: null,
    logoUrl: null,
    created_at: '2019-05-09T09:59:36.683Z',
    updated_at: '2019-05-15T12:46:03.542Z',
    type_fi: 'Oppilaitos',
    type_en: 'School',
    type_sv: 'Skola',
  },
  "fieldofstudy": {
    "id": 3,
    "name_fi": "Kauppa, hallinto ja oikeustiede",
    "name_en": "Kauppa, hallinto ja oikeustiede_en",
    "name_sv": "Kauppa, hallinto ja oikeustiede_sv",
    "created_at": "2019-05-07T09:33:01.518Z",
    "updated_at": "2019-05-13T09:23:09.600Z",
    "competences": [],
    },
  "created_at": "2019-05-09T10:01:07.693Z",
  "updated_at": "2019-05-15T12:46:03.550Z"
  },
  "created_at": "2019-05-09T10:01:27.377Z",
  "updated_at": "2019-05-24T10:00:03.895Z"
  },
  {
  "id": 2,
  "url": "https://wiki.humak.fi/display/OS/AHOT-ohjeet+opiskelijoille",
  "description_fi": "Valmentajakoulutus voidaan hyväksilukea Valmentava työote -opintojaksoon. Hyväksilukuun vaaditaan lisäksi näyttö kokonaisuuden keskeisten asioiden hallinnasta NQF6-tasolla. Jos samalla ei hyväksilueta partionjohtajakoulutusta, hyväksiluku edellyttää myös  toimintaa valmentajan pestissä partiossa.",
  "description_en": "Valmentajakoulutus voidaan hyväksilukea Valmentava työote -opintojaksoon. Hyväksilukuun vaaditaan lisäksi näyttö kokonaisuuden keskeisten asioiden hallinnasta NQF6-tasolla. Jos samalla ei hyväksilueta partionjohtajakoulutusta, hyväksiluku edellyttää myös  toimintaa valmentajan pestissä partiossa._en",
  "description_sv": "Valmentajakoulutus voidaan hyväksilukea Valmentava työote -opintojaksoon. Hyväksilukuun vaaditaan lisäksi näyttö kokonaisuuden keskeisten asioiden hallinnasta NQF6-tasolla. Jos samalla ei hyväksilueta partionjohtajakoulutusta, hyväksiluku edellyttää myös  toimintaa valmentajan pestissä partiossa._sv",
  "competence": {
  "id": 2,
  "identification": "partio-valmentajakoulutus",
  "name_en": "Valmentajakoulutus_EN",
  "description_en": "Valmentaja -koulutuksen käytyään partiojohtaja ymmärtää valmentamisen käsitteen ja osaa soveltaa valmentamisen toimintatapoja ja työkaluja pestissään. Hän ymmärtää partion aluetyön ja lippukuntatuen merkityksen sekä perusteet, ja osaa valmentaa lippukuntia kohti laadukkaampaa partiota. Hän osaa tukea lippukuntatoimijoita pesteissään ja varmistaa, että partion strategia sekä ajankohtaiset teemat nivotuvat osaksi lippukuntatoimintaa. Kouluttautuja osaa tukea ja valmentaa lippukunnan johtajistoa lippukunnan kokonaisuuden johtamisessa, partiokasvatuksen toteuttamisessa, henkilöstöresurssien kehittämisessä, lippukunnan lyhyen ja pitkän tähtäimen suunnittelussa ja erilaisten haasteiden ratkaisemisessa._en",
  "url": null,
  "name_fi": "Valmentajakoulutus",
  "name_sv": "Valmentajakoulutus_sv",
  "description_fi": "Valmentaja -koulutuksen käytyään partiojohtaja ymmärtää valmentamisen käsitteen ja osaa soveltaa valmentamisen toimintatapoja ja työkaluja pestissään. Hän ymmärtää partion aluetyön ja lippukuntatuen merkityksen sekä perusteet, ja osaa valmentaa lippukuntia kohti laadukkaampaa partiota. Hän osaa tukea lippukuntatoimijoita pesteissään ja varmistaa, että partion strategia sekä ajankohtaiset teemat nivotuvat osaksi lippukuntatoimintaa. Kouluttautuja osaa tukea ja valmentaa lippukunnan johtajistoa lippukunnan kokonaisuuden johtamisessa, partiokasvatuksen toteuttamisessa, henkilöstöresurssien kehittämisessä, lippukunnan lyhyen ja pitkän tähtäimen suunnittelussa ja erilaisten haasteiden ratkaisemisessa.",
  "description_sv": "Valmentaja -koulutuksen käytyään partiojohtaja ymmärtää valmentamisen käsitteen ja osaa soveltaa valmentamisen toimintatapoja ja työkaluja pestissään. Hän ymmärtää partion aluetyön ja lippukuntatuen merkityksen sekä perusteet, ja osaa valmentaa lippukuntia kohti laadukkaampaa partiota. Hän osaa tukea lippukuntatoimijoita pesteissään ja varmistaa, että partion strategia sekä ajankohtaiset teemat nivotuvat osaksi lippukuntatoimintaa. Kouluttautuja osaa tukea ja valmentaa lippukunnan johtajistoa lippukunnan kokonaisuuden johtamisessa, partiokasvatuksen toteuttamisessa, henkilöstöresurssien kehittämisessä, lippukunnan lyhyen ja pitkän tähtäimen suunnittelussa ja erilaisten haasteiden ratkaisemisessa._sv",
  "nqf": {
    "id": 3,
    "name_en": "Erikoisammattitukinnot_en",
    "name_fi": "Erikoisammattitukinnot",
    "name_sv": "Erikoisammattitukinnot_sv",
    "level": "5",
    "created_at": "2019-05-09T09:57:47.742Z",
    "updated_at": "2019-05-13T09:24:32.452Z"
  },
  "credits": null,
  "organization": {
    "id": 1,
    "name_en": "The Guides and Scouts of Finland",
    "name_fi": "Suomen Partiolaiset – Finlands Scouter ry",
    "name_sv": "Suomen Partiolaiset – Finlands Scouter ry",
    "description_fi": "Suomen Partiolaiset – Finlands Scouter ry on partioliikkeen keskusjärjestö Suomessa ja Suomen suurin nuorisojärjestö.",
    "description_en": "Suomen Partiolaiset – Finlands Scouter ry on partioliikkeen keskusjärjestö Suomessa ja Suomen suurin nuorisojärjestö._en",
    "description_sv": "Suomen Partiolaiset – Finlands Scouter ry on partioliikkeen keskusjärjestö Suomessa ja Suomen suurin nuorisojärjestö._sv",
    "url": "https://www.partio.fi",
    "logoUrl": null,
    "created_at": "2019-05-09T09:55:05.648Z",
    "updated_at": "2019-05-15T13:25:31.650Z",
  },
  "created_at": "2019-05-09T09:58:26.655Z",
  "updated_at": "2019-05-13T09:27:55.567Z"
  },
  "academicdegree": {
  "id": 1,
  "identification": "humak-yhteisopedagogi_amk",
  "name_en": "Yhteisöpedagogi (AMK)_EN",
  "name_fi": "Yhteisöpedagogi (AMK)",
  "name_sv": "Yhteisöpedagogi (AMK)_sv",
  "description_en": "Yhteisöpedagogitutkinnosta valmistuu arvostavan kohtaamisen ammattilaisia nuoriso- ja järjestötyöhön sekä yhä moninaisempiin ammatillisiin toimintaympäristöihin yhteiskunnan eri sektoreilla.  Työssä tarvitaan laajaa osaamista ihmisten kasvusta ja kehityksestä, yhteiskunnan rakenteesta ja toiminnasta sekä tietoa kulttuureista ja osallisuudesta. Yhteisöpedagogi (AMK) -tutkinnon voit suorittaa Humakissa kokopäiväisesti päivätoteutuksena tai rajallisen määrän lähijaksoja sisältävinä monimuoto-opintoina._en",
  "description_fi": "Yhteisöpedagogitutkinnosta valmistuu arvostavan kohtaamisen ammattilaisia nuoriso- ja järjestötyöhön sekä yhä moninaisempiin ammatillisiin toimintaympäristöihin yhteiskunnan eri sektoreilla.  Työssä tarvitaan laajaa osaamista ihmisten kasvusta ja kehityksestä, yhteiskunnan rakenteesta ja toiminnasta sekä tietoa kulttuureista ja osallisuudesta. Yhteisöpedagogi (AMK) -tutkinnon voit suorittaa Humakissa kokopäiväisesti päivätoteutuksena tai rajallisen määrän lähijaksoja sisältävinä monimuoto-opintoina.",
  "description_sv": "Yhteisöpedagogitutkinnosta valmistuu arvostavan kohtaamisen ammattilaisia nuoriso- ja järjestötyöhön sekä yhä moninaisempiin ammatillisiin toimintaympäristöihin yhteiskunnan eri sektoreilla.  Työssä tarvitaan laajaa osaamista ihmisten kasvusta ja kehityksestä, yhteiskunnan rakenteesta ja toiminnasta sekä tietoa kulttuureista ja osallisuudesta. Yhteisöpedagogi (AMK) -tutkinnon voit suorittaa Humakissa kokopäiväisesti päivätoteutuksena tai rajallisen määrän lähijaksoja sisältävinä monimuoto-opintoina._en",
  "url": null,
  "credits": null,
  "nqf": {
    "id": 3,
    "name_en": "Erikoisammattitukinnot_en",
    "name_fi": "Erikoisammattitukinnot",
    "name_sv": "Erikoisammattitukinnot_sv",
    "level": "5",
    "created_at": "2019-05-09T09:57:47.742Z",
    "updated_at": "2019-05-13T09:24:32.452Z"
  },
  "school": {
    id: 1,
    name_en: 'Humanistinen ammattikorkeakoulu_en',
    name_fi: 'Humanistinen ammattikorkeakoulu',
    name_sv: 'Humanistinen ammattikorkeakoulu_sv',
    description_en: 'Humanistinen ammattikorkeakoulu (Humak) on vahvasti profiloitunut, valtakunnallinen ammattikorkeakoulu, joka on erikoistunut järjestö- ja nuorisotyön, työyhteisöjen kehittämisen, kulttuurituotannon ja luovan toimialan yrittäjyyden sekä tulkkausalan erityisosaamisen ja toiminnan kehittämiseen. Humakissa on 1500 opiskelijaa ja noin 130 asiantuntijaa eri tehtävissä._en',
    description_fi: 'Humanistinen ammattikorkeakoulu (Humak) on vahvasti profiloitunut, valtakunnallinen ammattikorkeakoulu, joka on erikoistunut järjestö- ja nuorisotyön, työyhteisöjen kehittämisen, kulttuurituotannon ja luovan toimialan yrittäjyyden sekä tulkkausalan erityisosaamisen ja toiminnan kehittämiseen. Humakissa on 1500 opiskelijaa ja noin 130 asiantuntijaa eri tehtävissä.',
    description_sv: 'Humanistinen ammattikorkeakoulu (Humak) on vahvasti profiloitunut, valtakunnallinen ammattikorkeakoulu, joka on erikoistunut järjestö- ja nuorisotyön, työyhteisöjen kehittämisen, kulttuurituotannon ja luovan toimialan yrittäjyyden sekä tulkkausalan erityisosaamisen ja toiminnan kehittämiseen. Humakissa on 1500 opiskelijaa ja noin 130 asiantuntijaa eri tehtävissä._sv',
    url: null,
    logoUrl: null,
    created_at: '2019-05-09T09:59:36.683Z',
    updated_at: '2019-05-15T12:46:03.542Z',
    type_fi: 'Oppilaitos',
    type_en: 'School',
    type_sv: 'Skola',
  },
  "fieldofstudy": {
    "id": 3,
    "name_fi": "Kauppa, hallinto ja oikeustiede",
    "name_en": "Kauppa, hallinto ja oikeustiede_en",
    "name_sv": "Kauppa, hallinto ja oikeustiede_sv",
    "created_at": "2019-05-07T09:33:01.518Z",
    "updated_at": "2019-05-13T09:23:09.600Z",
    "competences": [],
    },
  "created_at": "2019-05-09T10:01:07.693Z",
  "updated_at": "2019-05-15T12:46:03.550Z"
  },
  "created_at": "2019-05-09T10:02:00.360Z",
  "updated_at": "2019-05-24T10:00:09.616Z"
  }
  ]
