export default [
  {
    id: 1,
    name_en: 'Humanistinen ammattikorkeakoulu_en',
    name_fi: 'Humanistinen ammattikorkeakoulu',
    name_sv: 'Humanistinen ammattikorkeakoulu_sv',
    description_en: 'Humanistinen ammattikorkeakoulu (Humak) on vahvasti profiloitunut, valtakunnallinen ammattikorkeakoulu, joka on erikoistunut järjestö- ja nuorisotyön, työyhteisöjen kehittämisen, kulttuurituotannon ja luovan toimialan yrittäjyyden sekä tulkkausalan erityisosaamisen ja toiminnan kehittämiseen. Humakissa on 1500 opiskelijaa ja noin 130 asiantuntijaa eri tehtävissä._en',
    description_fi: 'Humanistinen ammattikorkeakoulu (Humak) on vahvasti profiloitunut, valtakunnallinen ammattikorkeakoulu, joka on erikoistunut järjestö- ja nuorisotyön, työyhteisöjen kehittämisen, kulttuurituotannon ja luovan toimialan yrittäjyyden sekä tulkkausalan erityisosaamisen ja toiminnan kehittämiseen. Humakissa on 1500 opiskelijaa ja noin 130 asiantuntijaa eri tehtävissä.',
    description_sv: 'Humanistinen ammattikorkeakoulu (Humak) on vahvasti profiloitunut, valtakunnallinen ammattikorkeakoulu, joka on erikoistunut järjestö- ja nuorisotyön, työyhteisöjen kehittämisen, kulttuurituotannon ja luovan toimialan yrittäjyyden sekä tulkkausalan erityisosaamisen ja toiminnan kehittämiseen. Humakissa on 1500 opiskelijaa ja noin 130 asiantuntijaa eri tehtävissä._sv',
    url: null,
    logoUrl: null,
    created_at: '2019-05-09T09:59:36.683Z',
    updated_at: '2019-05-15T12:46:03.542Z',
    academicdegrees: [
      {
        id: 1,
        identification: 'humak-yhteisopedagogi_amk',
        name_en: 'Yhteisöpedagogi (AMK)_EN',
        name_fi: 'Yhteisöpedagogi (AMK)',
        name_sv: 'Yhteisöpedagogi (AMK)_sv',
        description_en: 'Yhteisöpedagogitutkinnosta valmistuu arvostavan kohtaamisen ammattilaisia nuoriso- ja järjestötyöhön sekä yhä moninaisempiin ammatillisiin toimintaympäristöihin yhteiskunnan eri sektoreilla.  Työssä tarvitaan laajaa osaamista ihmisten kasvusta ja kehityksestä, yhteiskunnan rakenteesta ja toiminnasta sekä tietoa kulttuureista ja osallisuudesta. Yhteisöpedagogi (AMK) -tutkinnon voit suorittaa Humakissa kokopäiväisesti päivätoteutuksena tai rajallisen määrän lähijaksoja sisältävinä monimuoto-opintoina._en',
        description_fi: 'Yhteisöpedagogitutkinnosta valmistuu arvostavan kohtaamisen ammattilaisia nuoriso- ja järjestötyöhön sekä yhä moninaisempiin ammatillisiin toimintaympäristöihin yhteiskunnan eri sektoreilla.  Työssä tarvitaan laajaa osaamista ihmisten kasvusta ja kehityksestä, yhteiskunnan rakenteesta ja toiminnasta sekä tietoa kulttuureista ja osallisuudesta. Yhteisöpedagogi (AMK) -tutkinnon voit suorittaa Humakissa kokopäiväisesti päivätoteutuksena tai rajallisen määrän lähijaksoja sisältävinä monimuoto-opintoina.',
        description_sv: 'Yhteisöpedagogitutkinnosta valmistuu arvostavan kohtaamisen ammattilaisia nuoriso- ja järjestötyöhön sekä yhä moninaisempiin ammatillisiin toimintaympäristöihin yhteiskunnan eri sektoreilla.  Työssä tarvitaan laajaa osaamista ihmisten kasvusta ja kehityksestä, yhteiskunnan rakenteesta ja toiminnasta sekä tietoa kulttuureista ja osallisuudesta. Yhteisöpedagogi (AMK) -tutkinnon voit suorittaa Humakissa kokopäiväisesti päivätoteutuksena tai rajallisen määrän lähijaksoja sisältävinä monimuoto-opintoina._en',
        url: null,
        credits: null,
        nqf: 4,
        school: 1,
        fieldofstudy: 1,
        created_at: '2019-05-09T10:01:07.693Z',
        updated_at: '2019-05-15T12:46:03.550Z'
      }
    ],
    type_fi: 'Oppilaitos',
    type_en: 'School',
    type_sv: 'Skola',
  },
  {
    id: 2,
    name_en: 'Haaga-Helia University of Applied Sciences',
    name_fi: 'Haaga-Helia ammattikorkeakoulu',
    name_sv: 'Haaga-Helia',
    description_en: 'Haaga-Helia is a strongly business orientated university of applied sciences in Finland. Through education, research and development, we prepare professionals for business and services. We focus on co-operation, entrepreneurship, innovation and internationality.',
    description_fi: 'Haaga-Helia ammattikorkeakoulu kouluttaa liike-elämän ja palveluelinkeinojen asiantuntijoita sekä tutkii ja kehittää näihin aloihin liittyvää osaamista ja toimintaa. Koulutusalamme ovat liiketalous, tietotekniikka, hotelli-, ravintola- ja matkailuala, johdon assistenttityö, toimittajakoulutus, liikunta-ala sekä ammatillinen opettajankoulutus. Meille on tärkeää, että opiskelijoillamme on heti valmistuttuaan vahvat siteet työelämään. Panostamme toiminnassamme yrittäjyyteen, yhteistyöhön, innovatiivisuuteen ja kansainvälisyyteen.',
    description_sv: 'Haaga-Helia University of Applied Sciences utbildar experter inom affärs- och serviceindustrin och forskar och utvecklar kompetens och aktiviteter inom dessa områden. Våra utbildningsområden omfattar företagsekonomi, informationsteknik, hotell, restaurang och turism, ledningsassistentarbete, journalistutbildning, sport och professionell lärarutbildning. Det är viktigt för oss att våra studenter har starka band med arbetslivet efter examen. Vi satsar på entreprenörskap, samarbete, innovation och internationalitet i vår verksamhet.',
    url: 'http://www.haaga-helia.fi/',
    logoUrl: null,
    created_at: '2019-05-16T08:16:09.159Z',
    updated_at: '2019-05-16T08:16:09.203Z',
    academicdegrees: [],
    type_fi: 'Oppilaitos',
    type_en: 'School',
    type_sv: 'Skola',
  },
  {
    id: 3,
    name_en: 'Metropolia University',
    name_fi: 'Metropolia Ammattikorkeakoulu',
    name_sv: 'Metropolia',
    description_en: 'Metropolia University of Applied Sciences, Finland’s largest university of applied sciences, educates the professionals of tomorrow in the fields of Business, Culture, Health care and Social services, and Technology.\n\nIn our community people and worlds meet to create insight, expertise and well-being for both the professional life and life in general. You can count on Metropolia as a reliable partner and an innovator in higher education. Through cooperation we discover new ideas and solutions to build a better future.\n\n',
    description_fi: 'Metropolia on pääkaupunkiseudulla toimiva kansainvälinen ja monialainen ammattikorkeakoulu. Koulutamme kulttuurin, liiketalouden, sosiaali- ja terveysalan sekä tekniikan asiantuntijoita ja kehittäjiä. Muodostamme yhteisön, jossa erilaiset ihmiset ja maailmat kohtaavat ja joka synnyttää oivalluksia ja osaamista työhön ja hyvinvointia elämään. Olemme vastuullinen kumppani ja korkeakoulutuksen uudistaja, joka yhteistyössä löytää uusia ratkaisuja ja rakentaa parempaa tulevaisuutta.\n\nVuoteen 2020 ulottuva strategiamme tähtää voimakkaasti uudistumiseen. Siinä korostuu tavoite vahvistaa Metropolian yhtenäisyyttä, osaamisen kehittämistä, kilpailukykyä ja yhteiskunnallista vaikuttavuutta. Tahtotilanamme on olla osaamisen rohkea uudistaja ja tulevaisuuden aktiivinen rakentaja.\n\nKeskitymme tulevina vuosina laadukkaaseen oppimiseen ja työelämäyhteistyöhön. Haluamme uudistaa toimintakulttuurimme ja osaamistamme digitalisaation sekä kehittyvien kampustemme myötä. Tutkimus-, kehittämis- ja innovaatiotoiminnassa sekä liiketoiminnassa haemme kasvua erityisesti vaikuttavuudessa ja ulkoisessa rahoituksessa.',
    description_sv: 'Metropolia tekniska högskolan, Finlands största vetenskaps universitet, utbildar morgondagens yrkesverksamma inom områdena Business, Culture, Health Care och Social Services, och Technology.\n\nI vårt samhälle möts människor och världar för att skapa insikt, kompetens och välbefinnande för både det professionella livet och livet i allmänhet. Du kan räkna med Metropolia som en pålitlig partner och en innovatör inom högre utbildning. Genom samarbete upptäcker vi nya idéer och lösningar för att skapa en bättre framtid.',
    url: 'https://www.metropolia.fi/',
    logoUrl: null,
    created_at: '2019-05-16T08:17:56.040Z',
    updated_at: '2019-05-16T08:17:56.083Z',
    academicdegrees: [],
    type_fi: 'Oppilaitos',
    type_en: 'School',
    type_sv: 'Skola',
  },
  {
    id: 4,
    name_en: 'University of Helsinki',
    name_fi: 'Helsingin yliopisto',
    name_sv: 'Helsingin yliopisto',
    description_en: 'The University of Helsinki seeks solutions for global challenges and creates new ways of thinking for the best of humanity. Through the power of science and research, the University has contributed to society, education and welfare since 1640. We have educated nine presidents and thousands of people at the top of politics, science, culture and economics. Not to mention four Nobel prize winners.',
    description_fi: 'Helsingin yliopisto on Suomen suurin ja vanhin tiedekorkeakoulu. Vuodesta 1640 se on ollut mukana luomassa reilua ja tasa-arvoista yhteiskuntaa, jota monilla mittareilla pidetään maailman parhaana. Tänään monitieteinen tiedeyhteisö ratkoo ongelmia, jotka koskettavat meistä jokaista, myös kansainvälisesti. 40 000 opiskelijan ja työntekijän tiedeyhteisö synnyttää ratkaisuja, jotka muotoilevat planeettamme ja koko ihmiskunnan tulevaisuutta.',
    description_sv: 'Helsingfors universitet är det största och äldsta universitetet i Finland. Sedan 1640 har det varit inblandat i att skapa ett rättvist och lika samhälle, vilket av många anses vara det bästa i världen. Idag löser det tvärvetenskapliga samhället de problem som påverkar oss alla, även internationellt. Det vetenskapliga samfundet på 40 000 studenter och medarbetare skapar lösningar som formar vår planet och hela mänsklighetens framtid.',
    url: 'https://www.helsinki.fi',
    logoUrl: null,
    created_at: '2019-05-16T08:21:54.465Z',
    updated_at: '2019-05-16T08:21:54.504Z',
    academicdegrees: [],
    type_fi: 'Oppilaitos',
    type_en: 'School',
    type_sv: 'Skola',
  },
  {
    id: 5,
    name_en: 'Aalto University',
    name_fi: 'Aalto-yliopisto',
    name_sv: 'Aalto-yliopisto',
    description_en: 'Aalto University is a multidisciplinary community of bold thinkers, where science and art meet technology and business. We are committed to identifying and solving grand societal challenges and building an innovative future.',
    description_fi: 'Aalto-yliopisto on monialainen tiedeyhteisö, jossa tiede ja taide kohtaavat tekniikan ja talouden. Rakennamme innovatiivista yhteiskuntaa korkeatasoisen tutkimuksen, opetuksen ja taiteellisen toiminnan keinoin.',
    description_sv: 'Aalto-universitetet är en flervetenskaplig gemenskap av modiga tänkare, där konst och vetenskap möter teknik och ekonomi. Vi bygger ett innovativt samhälle med hjälp av högklassig forskning, undervisning och konstnärlig verksamhet. ',
    url: 'https://www.aalto.f',
    logoUrl: null,
    created_at: '2019-05-16T08:23:36.156Z',
    updated_at: '2019-05-16T08:23:36.196Z',
    academicdegrees: [],
    type_fi: 'Oppilaitos',
    type_en: 'School',
    type_sv: 'Skola',
  },
  {
    id: 6,
    name_en: 'Laurea University of Applied Sciences',
    name_fi: 'Laurea-ammattikorkeakoulu',
    name_sv: 'Laurea-ammattikorkeakoulu',
    description_en: 'Laurea University of Applied Sciences operates in Uusimaa region at six different campuses. There are about 7800 students, 500 staff members and more than 24 000 alumni in our community.',
    description_fi: 'Olemme kuudella kampuksella Uudellamaalla toimiva ammattikorkeakoulu. Yhteisöömme kuuluu noin 7 800 opiskelijaa, 500 henkilökunnan jäsentä sekä yli 24 000 alumnia.',
    description_sv: 'Vi är ett sex-universitets universitet för tillämpad vetenskap i Uusimaa. Vårt samhälle omfattar cirka 7 800 studenter, 500 anställda och över 24 000 alumni.',
    url: 'https://www.laurea.fi',
    logoUrl: null,
    created_at: '2019-05-16T08:24:58.052Z',
    updated_at: '2019-05-16T08:24:58.093Z',
    academicdegrees: [
      {
        id: 2,
        identification: 'laurea-amk-liiketalous',
        name_en: 'Service Business Management',
        name_fi: 'Liiketalouden koulutus',
        name_sv: 'Service Business Management',
        description_en: 'Students of business management need the right attitude and ambition to get ahead in their career as well as the drive to develop both in Finland and internationally.',
        description_fi: 'Valmistuttuaan tradenomit osaavat myydä ja markkinoida, kehittää palveluita, verkostoitua sekä hoitaa taloushallinnon tehtäviä.',
        description_sv: 'Studerande i företagsledningen behöver rätt attityd och ambition att gå vidare i sin karriär samt att utveckla både i Finland och internationellt.',
        url: 'https://www.laurea.fi/koulutus/liiketalous-ja-tietojenkasittely/liiketalous-amk/',
        credits: 210,
        nqf: 4,
        school: 6,
        fieldofstudy: 3,
        created_at: '2019-05-16T08:27:50.932Z',
        updated_at: '2019-05-16T08:30:08.646Z'
      }
    ],
    type_fi: 'Oppilaitos',
    type_en: 'School',
    type_sv: 'Skola',
},
  {
    id: 1,
    name_en: 'The Guides and Scouts of Finland',
    name_fi: 'Suomen Partiolaiset – Finlands Scouter ry',
    name_sv: 'Suomen Partiolaiset – Finlands Scouter ry',
    description_fi: 'Suomen Partiolaiset – Finlands Scouter ry on partioliikkeen keskusjärjestö Suomessa ja Suomen suurin nuorisojärjestö.',
    description_en: 'Suomen Partiolaiset – Finlands Scouter ry on partioliikkeen keskusjärjestö Suomessa ja Suomen suurin nuorisojärjestö._en',
    description_sv: 'Suomen Partiolaiset – Finlands Scouter ry on partioliikkeen keskusjärjestö Suomessa ja Suomen suurin nuorisojärjestö._sv',
    url: 'https://www.partio.fi',
    logoUrl: null,
    created_at: '2019-05-09T09:55:05.648Z',
    updated_at: '2019-05-15T13:25:31.650Z',
    competences: [
      {
        id: 1,
        identification: 'partio-johtajan_peruskoulutus',
        name_en: 'Partiojohtajan peruskoulutus_en',
        description_en: 'Partiojohtaja -peruskoulutus on Suomen Partiolaiset ry:n johtamiskoulutusta. Koulutuksen suorituksesta saatava valtakirja on edellytys tietyissä partiotehtävissä esim. leirinjohtajana toimimiselle. Lähiopetuksen lisäksi kouluttautuja toteuttaa johtamistehtävän, jonka aikana hän johtaa ja ohjaa muita aikuisia tapahtuman tms. toteuttamiseksi. Kouluttautujan tukena johtamistehtävän aikana on aikuinen ohjaaja. Koulutukseen sisältyy maastoyöpyminen, jonka avulla opitaan perusleiritaitoja ja turvallisen maastotoiminnan perusteita. Partiojohtaja -peruskoulutuksen suoritettuaan partiojohtaja osaa perustaidot ja tiedot tapahtuman ja ihmisten johtamisesta, partio-ohjelmasta sekä lippukunnan (paikallisyhdistys) toiminnasta._en',
        url: null,
        name_fi: 'Partiojohtajan peruskoulutus',
        name_sv: 'Partiojohtajan peruskoulutus_sv',
        description_fi: 'Partiojohtaja -peruskoulutus on Suomen Partiolaiset ry:n johtamiskoulutusta. Koulutuksen suorituksesta saatava valtakirja on edellytys tietyissä partiotehtävissä esim. leirinjohtajana toimimiselle. Lähiopetuksen lisäksi kouluttautuja toteuttaa johtamistehtävän, jonka aikana hän johtaa ja ohjaa muita aikuisia tapahtuman tms. toteuttamiseksi. Kouluttautujan tukena johtamistehtävän aikana on aikuinen ohjaaja. Koulutukseen sisältyy maastoyöpyminen, jonka avulla opitaan perusleiritaitoja ja turvallisen maastotoiminnan perusteita. Partiojohtaja -peruskoulutuksen suoritettuaan partiojohtaja osaa perustaidot ja tiedot tapahtuman ja ihmisten johtamisesta, partio-ohjelmasta sekä lippukunnan (paikallisyhdistys) toiminnasta.',
        description_sv: 'Partiojohtaja -peruskoulutus on Suomen Partiolaiset ry:n johtamiskoulutusta. Koulutuksen suorituksesta saatava valtakirja on edellytys tietyissä partiotehtävissä esim. leirinjohtajana toimimiselle. Lähiopetuksen lisäksi kouluttautuja toteuttaa johtamistehtävän, jonka aikana hän johtaa ja ohjaa muita aikuisia tapahtuman tms. toteuttamiseksi. Kouluttautujan tukena johtamistehtävän aikana on aikuinen ohjaaja. Koulutukseen sisältyy maastoyöpyminen, jonka avulla opitaan perusleiritaitoja ja turvallisen maastotoiminnan perusteita. Partiojohtaja -peruskoulutuksen suoritettuaan partiojohtaja osaa perustaidot ja tiedot tapahtuman ja ihmisten johtamisesta, partio-ohjelmasta sekä lippukunnan (paikallisyhdistys) toiminnasta._sv',
        nqf: 3,
        credits: null,
        organization: 1,
        created_at: '2019-05-09T09:56:07.855Z',
        updated_at: '2019-05-15T13:25:31.674Z'
      }
    ],
    type_fi: 'Organisaatio',
    type_en: 'Organisation',
    type_sv: 'Organisation',
  },
  {
    id: 2,
    name_en: 'Finnish Judo Association',
    name_fi: 'Suomen Judoliitto',
    name_sv: 'Suomen Judoliitto_sv',
    description_fi: 'Suomen Judoliitto ry on perustettu vuonna 1958. Vuodesta 1963 lähtien Judoliitto on toiminut suomalaisten judoseurojen keskusjärjestönä. Judoliitossa on 122 jäsenseuraa.\n\nJudoliitto on Kansainvälisen Judoliiton (IJF) ja Euroopan Judoliiton (EJU) jäsen. Judoliitto on jäsenenä Suomen Olympiakomiteassa, Suomen Paralympiakomiteassa ja Suomen Urheilutyönantajissa.',
    description_en: 'The Finnish Judit Association was founded in 1958. Since 1963 Judo has been a central organization of Finnish judo clubs. There are 122 member societies in Judo.\n\nJudaism is a member of the International Union of Judges (IJF) and the European Judicial Union (EJU). Judo Federation is a member of the Finnish Olympic Committee, the Finnish Paralympic Committee and Finnish Sports Workers.',
    description_sv: 'Finlands juditförening grundades 1958. Sedan 1963 har Judo varit en central organisation för finska judoklubbar. Det finns 122 medlemsorganisationer i Judo.\n\nJudendom är medlem i Internationella domstolen (IJF) och Europeiska rättsliga unionen (EJU). Judo Federation är medlem i Finlands Olympiska Kommitté, Finlands Paralympiska Kommitté och Finlands Sportarbetare.',
    url: 'https://www.judoliitto.fi/',
    logoUrl: null,
    created_at: '2019-05-16T08:10:07.135Z',
    updated_at: '2019-05-16T08:10:07.181Z',
    competences: [],
    type_fi: 'Organisaatio',
    type_en: 'Organisation',
    type_sv: 'Organisation',
  },
  {
    id: 3,
    name_en: 'The Marthas',
    name_fi: 'Martat',
    name_sv: 'Martat_sv',
    description_fi: 'Marttaliitto on keskusjärjestö, joka suunnittelee järjestön toimintaa ja julkaisee kotitalouksia varten ruokaan, ravitsemukseen, puutarhanhoitoon, ympäristöön, kodin talouteen ja kodinhoitoon liittyvää aineistoa. Marttaliiton jäseniä ovat marttapiirit, joissa ammattitutkinnon suorittaneet kotitalous- ja puutarha-asiantuntijat järjestävät kursseja ja opetusta sekä jäsenilleen että avoimesti kaikille. Marttayhdistyksiä ja toimintaryhmiä on yli 1 200 ja niissä on noin 46 000 jäsentä. Yhdistykset kokoontuvat marttailtoihin luentojen, opiskelun, kotitalouskurssien ja kädentaitojen merkeissä.',
    description_en: 'The Martha Organization is a Finnish home economics organization, founded in 1899 to promote well-being and quality of life in the home. It carries out cultural and civic education and does advocacy work in Finland.',
    description_sv: 'Martha är en central organisation som utformar organisationens verksamhet och publicerar material för mat, näring, trädgårdsarbete, miljö, hushållsekonomi och hushållning för hushåll. Marttis medlemmar är martyrkretsar, där professionellt kvalificerade hem- och trädgårdsexperter organiserar kurser och undervisning för sina medlemmar och öppet för alla. Det finns mer än 1 200 Martha-föreningar och åtgärdsgrupper med cirka 46 000 medlemmar. Föreningar samlas i martyrer för föreläsningar, studier, hemmakurser och hantverk.',
    url: 'https://www.martat.fi',
    logoUrl: null,
    created_at: '2019-05-16T08:13:09.603Z',
    updated_at: '2019-05-16T08:13:09.645Z',
    competences: [],
    type_fi: 'Organisaatio',
    type_en: 'Organisation',
    type_sv: 'Organisation',
  }
];
